CREATE TABLE crime_report (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crime_type VARCHAR2(50),
    location VARCHAR2(100),
    reported_at TIMESTAMP,
    status VARCHAR2(20)
);

CREATE TABLE patrol_resource (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR2(50),
    area_assigned VARCHAR2(50),
    availability_level NUMBER
);

CREATE TABLE surveillance_alert (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_type VARCHAR2(50),
    description VARCHAR2(255),
    alert_time TIMESTAMP,
    resolved NUMBER(1) DEFAULT 0
);
