name: CI/CD - SafeVille

on:
  push:
    branches: [ "main", "staging" ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run tests
        run: mvn test

  docker-deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: safevilleacrbr2025.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: docker build -t safevilleacrbr2025.azurecr.io/safevilleweb:prod .

      - name: Push Docker image
        run: docker push safevilleacrbr2025.azurecr.io/safevilleweb:prod

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: safevilleacrbr2025
          resourceGroup: safeville-rg
          containerAppName: safeville-app
          imageToDeploy: safevilleacrbr2025.azurecr.io/safevilleweb:prod
          location: brazilsouth
          environmentVariables: SPRING_PROFILES_ACTIVE=prod
