name: SafeVille CI/CD

on:
  push:
    branches:
      - main
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: safeville

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configure Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build com Maven
        run: mvn clean package -DskipTests

      - name: Docker login no Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login safevilleacr2025.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build da imagem Docker
        run: docker build -t safevilleacr2025.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push da imagem para ACR
        run: docker push safevilleacr2025.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Login no Azure via service principal
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: false

      - name: Deploy no Azure Web App (Staging ou Produção)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ github.ref == 'refs/heads/main' && 'safeville-webapp-prod' || 'safeville-staging-webapp' }}
          images: safevilleacr2025.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
