name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
          az acr login --name safevilleacr2025

      - name: Build and push Docker image
        run: |
          docker build -t safevilleacr2025.azurecr.io/safeville:staging .
          docker push safevilleacr2025.azurecr.io/safeville:staging

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: safeville-staging
          images: safevilleacr2025.azurecr.io/safeville:staging
