name: Deploy para Azure - Staging

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker login no ACR
        run: |
          az acr login --name safevilleacr2025

      - name: Build e push da imagem Docker
        run: |
          docker build -t safevilleacr2025.azurecr.io/safeville:staging .
          docker push safevilleacr2025.azurecr.io/safeville:staging

      - name: Atualiza container no WebApp
        run: |
          az webapp config container set \
            --name safeville-staging-webapp \
            --resource-group safeville-rg \
            --docker-custom-image-name safevilleacr2025.azurecr.io/safeville:staging \
            --docker-registry-server-url https://safevilleacr2025.azurecr.io
