name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Build Docker image
        run: |
          docker build -t safevilleacr2025.azurecr.io/safeville:staging .

      - name: Login to ACR
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login safevilleacr2025.azurecr.io \
            --username ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Push image to ACR
        run: |
          docker push safevilleacr2025.azurecr.io/safeville:staging

      - name: Deploy to Azure Web App (Staging)
        uses: azure/webapps-deploy@v2
        with:
          app-name: safeville-staging-webapp
          images: safevilleacr2025.azurecr.io/safeville:staging
